import type { LucideIcon } from 'lucide-react'
import {
  AtSign,
  BadgeCheck,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Camera,
  CheckCircle2,
  CircleDollarSign,
  CircleHelp,
  ClipboardList,
  Clock3,
  CreditCard,
  Download,
  FileCheck2,
  FileText,
  Gift,
  Globe2,
  GraduationCap,
  Hash,
  Heart,
  Image,
  Info,
  Landmark,
  Link2,
  LockKeyhole,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Package,
  Palette,
  PenLine,
  Phone,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  Tag,
  Ticket,
  Trophy,
  Upload,
  UserCheck,
  UserRound,
  Users,
  Video,
  WalletCards,
} from 'lucide-react'

export interface IconCatalogItem {
  id: string
  label: string
  keywords: string
  Icon: LucideIcon
}

export const iconCatalog: IconCatalogItem[] = [
  { id: 'sparkles', label: 'Parıltı', keywords: 'yeni özel öne çıkan', Icon: Sparkles },
  { id: 'badge-check', label: 'Onay rozeti', keywords: 'onay doğrulama güven', Icon: BadgeCheck },
  { id: 'heart', label: 'Kalp', keywords: 'favori sevgi', Icon: Heart },
  { id: 'camera', label: 'Kamera', keywords: 'fotoğraf görsel', Icon: Camera },
  { id: 'star', label: 'Yıldız', keywords: 'puan favori', Icon: Star },
  { id: 'calendar', label: 'Takvim', keywords: 'tarih etkinlik', Icon: CalendarDays },
  { id: 'clock', label: 'Saat', keywords: 'zaman süre', Icon: Clock3 },
  { id: 'map-pin', label: 'Konum', keywords: 'adres yer', Icon: MapPin },
  { id: 'ticket', label: 'Bilet', keywords: 'etkinlik giriş', Icon: Ticket },
  { id: 'users', label: 'Katılımcılar', keywords: 'kişi ekip topluluk', Icon: Users },
  { id: 'user', label: 'Kullanıcı', keywords: 'kişi profil', Icon: UserRound },
  { id: 'user-check', label: 'Doğrulanmış kullanıcı', keywords: 'kişi onay', Icon: UserCheck },
  { id: 'building', label: 'Bina', keywords: 'şirket kurum ofis', Icon: Building2 },
  { id: 'briefcase', label: 'Çanta', keywords: 'iş kariyer', Icon: BriefcaseBusiness },
  { id: 'graduation-cap', label: 'Mezuniyet', keywords: 'öğrenci eğitim', Icon: GraduationCap },
  { id: 'mail', label: 'E-posta', keywords: 'mail iletişim', Icon: Mail },
  { id: 'at-sign', label: 'Et işareti', keywords: 'e-posta kullanıcı', Icon: AtSign },
  { id: 'phone', label: 'Telefon', keywords: 'iletişim arama', Icon: Phone },
  { id: 'globe', label: 'Dünya', keywords: 'web ülke dil', Icon: Globe2 },
  { id: 'link', label: 'Bağlantı', keywords: 'url link', Icon: Link2 },
  { id: 'message', label: 'Mesaj', keywords: 'iletişim sohbet', Icon: MessageCircle },
  { id: 'file-text', label: 'Belge', keywords: 'dosya metin form', Icon: FileText },
  { id: 'file-check', label: 'Onaylı belge', keywords: 'dosya onay', Icon: FileCheck2 },
  { id: 'clipboard', label: 'Pano', keywords: 'form liste', Icon: ClipboardList },
  { id: 'image', label: 'Görsel', keywords: 'resim medya', Icon: Image },
  { id: 'video', label: 'Video', keywords: 'medya film', Icon: Video },
  { id: 'upload', label: 'Yükle', keywords: 'dosya yükleme', Icon: Upload },
  { id: 'download', label: 'İndir', keywords: 'dosya indirme', Icon: Download },
  { id: 'bell', label: 'Bildirim', keywords: 'uyarı bildirim', Icon: Bell },
  { id: 'megaphone', label: 'Duyuru', keywords: 'bildirim kampanya', Icon: Megaphone },
  { id: 'gift', label: 'Hediye', keywords: 'kampanya avantaj', Icon: Gift },
  { id: 'trophy', label: 'Kupa', keywords: 'başarı ödül', Icon: Trophy },
  { id: 'tag', label: 'Etiket', keywords: 'kategori fiyat', Icon: Tag },
  { id: 'package', label: 'Paket', keywords: 'ürün gönderi', Icon: Package },
  { id: 'wallet', label: 'Cüzdan', keywords: 'ödeme para', Icon: WalletCards },
  { id: 'credit-card', label: 'Kart', keywords: 'ödeme banka', Icon: CreditCard },
  { id: 'money', label: 'Para', keywords: 'ödeme ücret fiyat', Icon: CircleDollarSign },
  { id: 'landmark', label: 'Finans', keywords: 'banka vergi', Icon: Landmark },
  { id: 'lock', label: 'Kilit', keywords: 'güvenlik gizlilik', Icon: LockKeyhole },
  { id: 'shield-check', label: 'Güvenli', keywords: 'güvenlik doğrulama', Icon: ShieldCheck },
  { id: 'check-circle', label: 'Tamamlandı', keywords: 'başarılı onay', Icon: CheckCircle2 },
  { id: 'info', label: 'Bilgi', keywords: 'yardım açıklama', Icon: Info },
  { id: 'help', label: 'Yardım', keywords: 'soru destek', Icon: CircleHelp },
  { id: 'palette', label: 'Tasarım', keywords: 'renk tema görünüm', Icon: Palette },
  { id: 'settings', label: 'Ayar', keywords: 'ayar yapılandırma', Icon: Settings2 },
  { id: 'edit', label: 'Düzenle', keywords: 'metin yazı', Icon: PenLine },
  { id: 'search', label: 'Ara', keywords: 'arama bul', Icon: Search },
  { id: 'send', label: 'Gönder', keywords: 'gönder paylaş', Icon: Send },
  { id: 'hash', label: 'Numara', keywords: 'sayı numara', Icon: Hash },
]

const iconsById = new Map(iconCatalog.map((item) => [item.id, item.Icon]))

export function getIconComponent(iconName: string | undefined): LucideIcon {
  return iconsById.get(iconName || '') || Sparkles
}
