import assert from 'node:assert'
import { readFileSync } from 'node:fs'

const palette = readFileSync('src/components/mavenforms/builder/field-palette.tsx', 'utf8')
const builder = readFileSync('src/components/mavenforms/views/form-builder-view.tsx', 'utf8')
const documentSource = readFileSync('src/lib/form-document.ts', 'utf8')

assert(palette.includes('Responsive düzen') && palette.includes('Yerleşim sihirbazı') && palette.includes('bento-featured'), 'left panel must expose an optional Grid/Bento guide')
assert(palette.includes('layoutGuideOpen') && palette.includes('CollapsibleContent'), 'layout guide must stay secondary to field editing')
assert(palette.includes('disabled={fieldCount === 0}'), 'layout wizard must be disabled when there are no fields')
assert(builder.includes('createLayoutPreset') && builder.includes('updates: nextFields.map'), 'wizard must persist all field layouts in one batch')
assert(documentSource.includes('export function createLayoutPreset'), 'layout presets must be generated by a shared contract')

console.log('builder-layout-wizard.test: PASS (AC-LAYOUT-04)')
