import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { safePath, snapshot, changedFiles, assertScope, execute } from '../scripts/workflow.mjs';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'mavenforms-workflow-'));
const write = (name, value) => { fs.mkdirSync(path.dirname(path.join(root, name)), { recursive: true }); fs.writeFileSync(path.join(root, name), value); };
write('source.ts', 'export const value = 1');
write('.env', 'EXAMPLE=excluded');
assert.throws(() => safePath(root, '../escape'), /relative/);
assert.throws(() => safePath(root, 'C:\\escape'), /relative/);
assert(!Object.keys(snapshot(root)).includes('.env'));
assert.deepEqual(changedFiles({ 'a.ts': 'old' }, { 'b.ts': 'new' }), ['a.ts', 'b.ts']);
assert.throws(() => assertScope(['src-other/a.ts'], ['src/**']), /out-of-scope/);
const packet = { id: 'TEST-01', status: 'READY', timeboxMinutes: 15, sourceOfTruth: 'docs/MavenForms_Platform_Core_Master_Plan_2026-09-17/', goal: 'test', rollback: 'restore fixture', previous: [], reads: ['source.ts'], acceptance: ['real command'], allowedFiles: ['source.ts'], preflight: [['node', '-e', 'process.exit(0)']], checks: [['node', '-e', 'process.exit(0)']] };
write('packet.json', JSON.stringify(packet));
assert.throws(() => execute(root, 'verify', 'packet.json'), /ENOENT/);
execute(root, 'begin', 'packet.json');
assert.throws(() => execute(root, 'verify', 'packet.json'), /no in-scope change/);
write('other.ts', 'unexpected');
assert.throws(() => execute(root, 'verify', 'packet.json'), /out-of-scope/);
fs.unlinkSync(path.join(root, 'other.ts'));
write('source.ts', 'export const value = 2');
execute(root, 'verify', 'packet.json');
const receipt = JSON.parse(fs.readFileSync(path.join(root, 'artifacts/workflow/TEST-01/verified.json')));
assert.equal(receipt.releaseVerified, false);
assert.deepEqual(receipt.changedFiles, ['source.ts']);
assert.throws(() => execute(root, 'verify', 'packet.json'), /EEXIST/);
write('next.json', JSON.stringify({ ...packet, id: 'TEST-02', previous: ['TEST-01'] }));
write('source.ts', 'changed after verification');
assert.throws(() => execute(root, 'begin', 'next.json'), /evidence stale/);
write('fail.json', JSON.stringify({ ...packet, id: 'FAIL-01', checks: [['node', '-e', 'process.exit(1)']] }));
execute(root, 'begin', 'fail.json');
write('source.ts', 'change before failed verification');
assert.throws(() => execute(root, 'verify', 'fail.json'), /command failed/);
assert(!fs.existsSync(path.join(root, 'artifacts/workflow/FAIL-01/verified.json')));
write('changed.json', JSON.stringify({ ...packet, id: 'CHANGED-01' }));
execute(root, 'begin', 'changed.json');
write('changed.json', JSON.stringify({ ...packet, id: 'CHANGED-01', goal: 'silently changed scope' }));
assert.throws(() => execute(root, 'verify', 'changed.json'), /packet changed/);
console.log('workflow.test: PASS');
